_BASE_: "baseline.yaml"
DATASETS:
  TRAIN: ("bjtu_train",)
  TEST: ["bjtu_test"]
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0125
  MAX_ITER: 250
  STEPS: []
MODEL:
  WEIGHTS: pretrained/model_final_f6e8b1.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 6
TEST:
  EVAL_PERIOD: 50
OUTPUT_DIR: result/baseline_faster_r101_b16_s250
BASE_MODEL: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
VERSION: 2
