DATASETS:
  TRAIN: ("bjtu_train",)
  TEST: ["bjtu_test"]
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0125
  MAX_ITER: 250
  STEPS: []
MODEL:
  WEIGHTS: pretrained/model_final_280758.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 6
TEST:
  EVAL_PERIOD: 50
OUTPUT_DIR: result/baseline_faster_r50_b16_s250
VERSION: 2
