_BASE_: "faster_rcnn_R_50_FPN_3x.yaml"
DATASETS:
  TRAIN: ("bjtu_train_washed",)
  TEST: ["bjtu_test_washed"]
OUTPUT_DIR: result/hit_lr_test
MODEL:
  WEIGHTS: pretrained/R50.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 6
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 1e-3
  BASE_LR_END: 1e-4
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 30000
INPUT:
  RANDOM_FLIP: none
  CROP: 
    ENABLED: true
    TYPE: relative_range
    SIZE: [0.7, 0.7]

