_BASE_: "faster_rcnn_R_50_FPN_3x.yaml"
DATASETS:
  TRAIN: ("RCTW_train",)
OUTPUT_DIR: result/pretrain_text
MODEL:
  WEIGHTS: pretrained/R50.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 7e-3
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 3000
INPUT:
  RANDOM_FLIP: none
  CROP: 
    ENABLED: true
    TYPE: relative_range
    SIZE: [0.7, 0.7]
